name: hola mundo

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: Holamundo1
      run: echo "hola mundo"
  
  other:
    runs-on: ubuntu-latest
    needs: hola
    steps:
    - name: LS
      run: ls -al
